[allowlist]
description = "Allowlist for known safe secrets and files"

files = [
  "seeds.sql",
  "scripts/seeds/.*\\.ts",
  "\\.env\\.example",
  "gitleaks-report.json"
]

paths = [
  "scripts/seeds",
  "supabase/fixtures"
]

commitAuthor = ["dependabot"]
