# .gitguardian.yml

# Optional: you can specify the version
version: 2

# Ignore specific files or directories
paths-ignore:
  - ".env.example"
# Optional: define custom detectors (if needed)
# detectors:
#   - name: "Custom AWS Key"
#     match: "AKIA[0-9A-Z]{16}"
#     severity: "high"
#     description: "AWS Access Key"
