# .semgrep.yml
rules:
  # Semgrep’s published rule packs
  - p/default
  - p/owasp-top-ten

  # Your own custom rules
  - security/semgrep/general.yml

exclude:
  # Skip seed data with known bcrypt hashes
  - supabase/seed.sql

# Turn off registry‐usage metrics
metrics: off
