#!/bin/bash
# Prevent committing secrets
echo "✅ Pre-commit hook ran"

echo "🕵️‍♀️ Running Gitleaks protect (pre-commit)..."

if ! gitleaks protect --staged --verbose --config=.gitleaks.toml; then
  echo "🛑 Gitleaks detected secrets. Aborting commit."
  exit 1
fi
