version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"  # root of the project
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "eslint"
        versions: ["<8.0.0"]
