name: Auto-merge Dependabot security updates

on:
  pull_request_target:
    types: [opened, reopened, labeled, unlabeled, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    # only run on Dependabot PRs that have the “security” label
    if: |
      github.actor == 'dependabot[bot]' &&
      contains(github.event.pull_request.labels.*.name, 'security')
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve Dependabot security PR
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # restrict to Security updates only
          # hmarr/auto-approve-action@v2 satisfies the 1-reviewer requirement automatically

      - name: Enable auto-merge for security fixes
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
