name: Auto-merge Dependabot security updates

on:
  pull_request_target:
    types: [opened, reopened, labeled, unlabeled, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: |
      github.actor == 'NickTheDevOpsGuy' &&
      contains(github.event.pull_request.labels.*.name, 'security')
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Auto-approve Dependabot security PR
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.MERGE_TOKEN }}

      - name: ✅ Enable auto-merge for security fixes
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.MERGE_TOKEN }}
          pull-request-number: ${{ github.event.number }}
          merge-method: squash
