name: Prettier Formatting Check

on:
  pull_request:
    branches: [main, development]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: |
          npx prettier --config .prettierrc.yml --check . \!supabase/**/*.types.ts
