name: Renovate
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"  # hourly
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/github-action@v40.1.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: debug
