name: Semgrep Scan

# triggers
on:
  pull_request:
    branches:
      - development

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run Semgrep via Docker
        run: npm run semgrep