name: Semgrep Scan

# triggers
on:
  pull_request:
    branches:
      - development

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep:1.127.1

    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep scan
        run: |
          semgrep scan \
            --config p/default \
            --config p/owasp-top-ten \
            --config security/semgrep/general.yml \
            --exclude supabase/seed.sql \
            --metrics=off \
            --error
