name: Semgrep Scan

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install Semgrep from PyPI
      - name: Install Semgrep
        run: pip install semgrep

      # 4. Run Semgrep scan
      - name: Run Semgrep scan
        run: |
          semgrep scan \
            --config p/default \
            --config p/owasp-top-ten \
            --config ./security/semgrep \
            --exclude supabase/seed.sql \
            --metrics=off \
            --error
